import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Couture Greek",
  description: "Generated by create next app",
  url: "https://couture-greek.vercel.app",
  openGraph: {
    title: "Couture Greek",
    description: "Generated by create next app",
    url: "https://couture-greek.vercel.app",
    siteName: "Couture Greek",  
    images: [
      {
        url: "https://couture-greek.vercel.app/og.png",
        width: 1200,
        height: 630,
        alt: "Couture Greek OG Image",
      },
    ],
    locale: "en_US",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
